/**
 * Get full country name from IOC/ISO code
 * Centralized mapping for consistent country name display
 */
export function getCountryName(isoCode: string): string {
  const nameMap: Record<string, string> = {
    // Europe
    GER: 'Germany',
    NED: 'Netherlands',
    SUI: 'Switzerland',
    CRO: 'Croatia',
    SLO: 'Slovenia',
    LAT: 'Latvia',
    POR: 'Portugal',
    GRE: 'Greece',
    DEN: 'Denmark',
    SWE: 'Sweden',
    NOR: 'Norway',
    FIN: 'Finland',
    AUT: 'Austria',
    BEL: 'Belgium',
    CZE: 'Czech Republic',
    POL: 'Poland',
    HUN: 'Hungary',
    ROU: 'Romania',
    BUL: 'Bulgaria',
    SVK: 'Slovakia',
    SRB: 'Serbia',
    UKR: 'Ukraine',
    BLR: 'Belarus',
    LTU: 'Lithuania',
    EST: 'Estonia',
    IRL: 'Ireland',
    ESP: 'Spain',
    ITA: 'Italy',
    FRA: 'France',
    GBR: 'Great Britain',
    ENG: 'England',
    SCO: 'Scotland',
    WAL: 'Wales',
    NIR: 'Northern Ireland',
    ISL: 'Iceland',
    LUX: 'Luxembourg',
    MLT: 'Malta',
    CYP: 'Cyprus',
    MNE: 'Montenegro',
    MKD: 'North Macedonia',
    BIH: 'Bosnia and Herzegovina',
    ALB: 'Albania',
    MDA: 'Moldova',
    ARM: 'Armenia',
    GEO: 'Georgia',
    AZE: 'Azerbaijan',
    RUS: 'Russia',
    TUR: 'Turkey',

    // Asia & Middle East
    CHN: 'China',
    JPN: 'Japan',
    KOR: 'South Korea',
    TPE: 'Chinese Taipei',
    HKG: 'Hong Kong',
    IND: 'India',
    THA: 'Thailand',
    MAS: 'Malaysia',
    SGP: 'Singapore',
    INA: 'Indonesia',
    PHI: 'Philippines',
    VIE: 'Vietnam',
    PAK: 'Pakistan',
    BAN: 'Bangladesh',
    SRI: 'Sri Lanka',
    NEP: 'Nepal',
    IRN: 'Iran',
    IRQ: 'Iraq',
    ISR: 'Israel',
    JOR: 'Jordan',
    LIB: 'Lebanon',
    SYR: 'Syria',
    KSA: 'Saudi Arabia',
    UAE: 'United Arab Emirates',
    KUW: 'Kuwait',
    QAT: 'Qatar',
    BRN: 'Bahrain',
    OMA: 'Oman',
    YEM: 'Yemen',
    KAZ: 'Kazakhstan',
    UZB: 'Uzbekistan',
    TKM: 'Turkmenistan',
    KGZ: 'Kyrgyzstan',
    TJK: 'Tajikistan',
    MGL: 'Mongolia',

    // Americas
    USA: 'United States',
    CAN: 'Canada',
    MEX: 'Mexico',
    BRA: 'Brazil',
    ARG: 'Argentina',
    CHI: 'Chile',
    COL: 'Colombia',
    PER: 'Peru',
    VEN: 'Venezuela',
    ECU: 'Ecuador',
    URU: 'Uruguay',
    PAR: 'Paraguay',
    BOL: 'Bolivia',
    CRC: 'Costa Rica',
    PAN: 'Panama',
    GUA: 'Guatemala',
    HON: 'Honduras',
    ESA: 'El Salvador',
    NCA: 'Nicaragua',
    CUB: 'Cuba',
    DOM: 'Dominican Republic',
    PUR: 'Puerto Rico',
    JAM: 'Jamaica',
    TRI: 'Trinidad and Tobago',
    BAR: 'Barbados',
    BAH: 'Bahamas',
    HAI: 'Haiti',
    GUY: 'Guyana',
    SUR: 'Suriname',

    // Africa
    RSA: 'South Africa',
    EGY: 'Egypt',
    ETH: 'Ethiopia',
    KEN: 'Kenya',
    NGR: 'Nigeria',
    GHA: 'Ghana',
    TAN: 'Tanzania',
    UGA: 'Uganda',
    ALG: 'Algeria',
    MAR: 'Morocco',
    TUN: 'Tunisia',
    ZIM: 'Zimbabwe',
    ZAM: 'Zambia',
    BOT: 'Botswana',
    NAM: 'Namibia',
    CMR: 'Cameroon',
    CIV: 'Ivory Coast',
    SEN: 'Senegal',
    ANG: 'Angola',
    MOZ: 'Mozambique',
    MRI: 'Mauritius',
    MAD: 'Madagascar',
    LBA: 'Libya',
    SUD: 'Sudan',
    SLE: 'Sierra Leone',
    LBR: 'Liberia',
    GAM: 'Gambia',
    GUI: 'Guinea',
    GBS: 'Guinea-Bissau',
    BUR: 'Burkina Faso',
    MLI: 'Mali',
    NIG: 'Niger',
    CHA: 'Chad',
    CAF: 'Central African Republic',
    CGO: 'Congo',
    COD: 'DR Congo',
    GAB: 'Gabon',
    GEQ: 'Equatorial Guinea',
    RWA: 'Rwanda',
    BDI: 'Burundi',
    ERI: 'Eritrea',
    DJI: 'Djibouti',
    SOM: 'Somalia',
    TOG: 'Togo',
    BEN: 'Benin',
    LES: 'Lesotho',
    SWZ: 'Eswatini',
    MAW: 'Malawi',

    // Oceania
    AUS: 'Australia',
    NZL: 'New Zealand',
    FIJ: 'Fiji',
    PNG: 'Papua New Guinea',
    SAM: 'Samoa',
    TON: 'Tonga',
    COK: 'Cook Islands',
    SOL: 'Solomon Islands',
    VAN: 'Vanuatu',
  }

  return nameMap[isoCode] || isoCode
}
